package export

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/jcrussell/livermore-budget/internal/export"
	"github.com/jcrussell/livermore-budget/internal/fact"
	"github.com/jcrussell/livermore-budget/internal/project"
)

// repoRootForTest is the checkout these tests build from.
func repoRootForTest(t *testing.T) string {
	t.Helper()
	root, err := filepath.Abs(filepath.Join("..", "..", ".."))
	if err != nil {
		t.Fatalf("resolve repo root: %v", err)
	}
	return root
}

// factRow is the part of a committed fact this file needs.
type factRow struct {
	ID          string `json:"id"`
	AmountCents int64  `json:"amount_cents"`
}

// committedFacts reads the audit trail CI compares byte for byte.
func committedFacts(t *testing.T) map[string]int64 {
	t.Helper()
	path := filepath.Join("..", "..", "..", "facts", "facts.jsonl")
	f, err := os.Open(path) // #nosec G304 -- a fixed path inside the repository.
	if err != nil {
		t.Fatalf("open %s: %v", path, err)
	}
	defer func() { _ = f.Close() }()

	out := map[string]int64{}
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 4*1024*1024)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" {
			continue
		}
		var row factRow
		if err := json.Unmarshal([]byte(line), &row); err != nil {
			t.Fatalf("parse %s: %v", path, err)
		}
		out[row.ID] = row.AmountCents
	}
	if err := sc.Err(); err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	if len(out) == 0 {
		t.Fatalf("%s carries no facts, so this test asserts nothing", path)
	}
	return out
}

// The column is held to facts/facts.jsonl, not to the files it replaces: a
// golden regenerated by the commit that changes the format is green by
// construction. A derived link cites nothing and is counted rather than skipped.
//
// Why, measured: docs/schema-contracts.md.
func TestEveryColumnLinkEqualsTheFactsItCites(t *testing.T) {
	facts := committedFacts(t)
	built, err := buildAll(repoRootForTest(t))
	if err != nil {
		t.Fatalf("buildAll: %v", err)
	}
	columns, _, err := export.ColumnsOf(built.Projections, "fisc test")
	if err != nil {
		t.Fatalf("columnsOf: %v", err)
	}
	if len(columns) == 0 {
		t.Fatal("no column document was built, so this test asserts nothing")
	}

	checked, derived, flipped := 0, 0, 0
	for name, col := range columns {
		for schedule, sched := range col.Schedules {
			for i, l := range sched.Links {
				if len(l.FactIDs) == 0 {
					if !l.Derived {
						t.Errorf("%s %s link %d cites no fact and is not marked derived; "+
							"every published figure carries a provenance pointer",
							name, schedule, i)
					}
					derived++
					continue
				}
				var sum int64
				missing := []string(nil)
				for _, id := range l.FactIDs {
					cents, ok := facts[id]
					if !ok {
						missing = append(missing, id)
						continue
					}
					sum += cents
				}
				if len(missing) > 0 {
					t.Errorf("%s %s link %d cites %v, which facts/facts.jsonl does not carry",
						name, schedule, i, missing)
					continue
				}
				// The draw leg carries its facts' negation, keyed on the source
				// id: "equals the absolute sum" would accept a reversed leg.
				want := sum
				if col.Nodes[l.From].ID == project.NodeFundBalanceDraw {
					want = -sum
					flipped++
				}
				if want != l.ValueCents {
					t.Errorf("%s %s link %d (%s -> %s) carries %d and its %d fact(s) come to %d",
						name, schedule, i, col.Nodes[l.From].ID, col.Nodes[l.To].ID,
						l.ValueCents, len(l.FactIDs), sum)
				}
				checked++
			}
		}
	}
	t.Logf("%d cited link(s) across %d column(s) equal the facts they cite, "+
		"%d of them the fund-balance draw carrying their negation; %d derived link(s) cite nothing",
		checked, len(columns), flipped, derived)
	// The allowance is not vacuous.
	if flipped == 0 {
		t.Error("no fund-balance draw was checked, so the one allowance this test " +
			"makes was never exercised and could be wrong")
	}
}

// The indices resolve. An off-by-one joins the wrong marks while every figure
// stays correct, which no fact check can see.
func TestEveryColumnIndexResolves(t *testing.T) {
	built, err := buildAll(repoRootForTest(t))
	if err != nil {
		t.Fatalf("buildAll: %v", err)
	}
	columns, _, err := export.ColumnsOf(built.Projections, "fisc test")
	if err != nil {
		t.Fatalf("columnsOf: %v", err)
	}
	for name, col := range columns {
		for schedule, sched := range col.Schedules {
			for _, n := range sched.Nodes {
				if n.Node < 0 || n.Node >= len(col.Nodes) {
					t.Fatalf("%s %s draws node %d of %d", name, schedule, n.Node, len(col.Nodes))
				}
			}
			for i, l := range sched.Links {
				if l.From < 0 || l.From >= len(col.Nodes) || l.To < 0 || l.To >= len(col.Nodes) {
					t.Fatalf("%s %s link %d joins %d -> %d, and the table holds %d",
						name, schedule, i, l.From, l.To, len(col.Nodes))
				}
			}
		}
	}
}

// TestEveryFundGroupNodeHasAPlaceInItsColumnsOrder: a column's fund_groups is
// exactly its fund_group nodes. site/app.js orders by the list with no
// fallback, so an omitted group would sort at -1.
func TestEveryFundGroupNodeHasAPlaceInItsColumnsOrder(t *testing.T) {
	built, err := buildAll(repoRootForTest(t))
	if err != nil {
		t.Fatalf("buildAll: %v", err)
	}
	columns, _, err := export.ColumnsOf(built.Projections, "fisc test")
	if err != nil {
		t.Fatalf("columnsOf: %v", err)
	}
	held := 0
	for name, col := range columns {
		listed := map[string]bool{}
		for _, g := range col.FundGroups {
			listed[g.ID] = true
		}
		nodes := map[string]bool{}
		for _, n := range col.Nodes {
			// The role vocabulary is schema/column.schema.json's; the schema
			// test beside this one holds the string.
			if n.Role != "fund_group" {
				continue
			}
			nodes[n.ID] = true
			if !listed[n.ID] {
				t.Errorf("%s carries fund-group node %s and its fund_groups omit it; the client would place it nowhere", name, n.ID)
			}
			held++
		}
		for id := range listed {
			if !nodes[id] {
				t.Errorf("%s lists %s among its fund groups and carries no such node", name, id)
			}
		}
	}
	if held == 0 {
		t.Fatal("no column carries a fund-group node, so this test holds nothing")
	}
	if !t.Failed() {
		t.Logf("%d fund-group node(s) across %d column(s), each in its column's order", held, len(columns))
	}
}

// exportedSite runs `fisc export` over the committed store into a temp dir.
func exportedSite(t *testing.T) string {
	t.Helper()
	opts, _, _, _ := testOptions(t)
	root := repoRootForTest(t)
	opts.RepoRoot = func() (string, error) { return root, nil }
	opts.Build = buildAll
	if err := exportRun(opts); err != nil {
		t.Fatalf("exportRun: %v", err)
	}
	return opts.OutputDir
}

// TestEveryServedColumnIsTheScheduleItFolds reads the four column files the
// export writes, not ColumnsOf: fy2024-actual.json and fy2025-revised.json
// have no golden. Each link's ends are the projection's, and its facts are of
// the column's year and basis, sum to its value and are the pages it cites.
func TestEveryServedColumnIsTheScheduleItFolds(t *testing.T) {
	dir := exportedSite(t)
	root := repoRootForTest(t)
	_, facts, err := readFactStore(root)
	if err != nil {
		t.Fatal(err)
	}
	byID := map[string]fact.Fact{}
	for _, f := range facts {
		byID[f.ID] = f
	}
	built, err := buildAll(root)
	if err != nil {
		t.Fatalf("buildAll: %v", err)
	}
	_, ix, err := export.ColumnsOf(built.Projections, "fisc test")
	if err != nil {
		t.Fatalf("ColumnsOf: %v", err)
	}
	for _, served := range []string{"fy2024-actual.json", "fy2025-revised.json", "fy2026-adopted.json", "fy2027-adopted.json"} {
		raw, err := os.ReadFile(filepath.Join(dir, served)) // #nosec G304 -- a temp dir this test wrote.
		if err != nil {
			t.Fatalf("fisc export wrote no %s: %v", served, err)
		}
		var col export.ColumnDoc
		if err := json.Unmarshal(raw, &col); err != nil {
			t.Fatalf("decode %s: %v", served, err)
		}
		cited := 0
		for schedule, sched := range col.Schedules {
			stem, ok := ix.Stem(served, schedule)
			if !ok {
				t.Errorf("%s serves schedule %s, which no built document is", served, schedule)
				continue
			}
			var doc struct {
				Links []struct{ Source, Target string } `json:"links"`
			}
			if err := json.Unmarshal(built.Projections[stem], &doc); err != nil {
				t.Fatalf("decode %s: %v", stem, err)
			}
			if len(doc.Links) != len(sched.Links) {
				t.Errorf("%s %s serves %d links and %s draws %d", served, schedule, len(sched.Links), stem, len(doc.Links))
				continue
			}
			for i, l := range sched.Links {
				at := fmt.Sprintf("%s %s link %d", served, schedule, i)
				if l.From < 0 || l.From >= len(col.Nodes) || l.To < 0 || l.To >= len(col.Nodes) {
					t.Errorf("%s joins %d -> %d of %d nodes", at, l.From, l.To, len(col.Nodes))
					continue
				}
				src, dst := col.Nodes[l.From].ID, col.Nodes[l.To].ID
				if src != doc.Links[i].Source || dst != doc.Links[i].Target {
					t.Errorf("%s is %s -> %s and %s draws %s -> %s", at, src, dst, stem, doc.Links[i].Source, doc.Links[i].Target)
				}
				for _, fault := range linkFactFaults(at, l, src, col.Column, byID) {
					t.Error(fault)
				}
				if len(l.FactIDs) > 0 {
					cited++
				}
			}
		}
		if cited == 0 {
			t.Errorf("%s serves no cited link, so nothing of it was held", served)
		}
	}
}
