package export

import (
	"bufio"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/jcrussell/livermore-budget/internal/export"
	"github.com/jcrussell/livermore-budget/internal/project"
)

// repoRootForTest is the checkout these tests build from.
func repoRootForTest(t *testing.T) string {
	t.Helper()
	root, err := filepath.Abs(filepath.Join("..", "..", ".."))
	if err != nil {
		t.Fatalf("resolve repo root: %v", err)
	}
	return root
}

// factRow is the part of a committed fact this file needs.
type factRow struct {
	ID          string `json:"id"`
	AmountCents int64  `json:"amount_cents"`
}

// committedFacts reads the audit trail CI compares byte for byte.
func committedFacts(t *testing.T) map[string]int64 {
	t.Helper()
	path := filepath.Join("..", "..", "..", "facts", "facts.jsonl")
	f, err := os.Open(path) // #nosec G304 -- a fixed path inside the repository.
	if err != nil {
		t.Fatalf("open %s: %v", path, err)
	}
	defer func() { _ = f.Close() }()

	out := map[string]int64{}
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 4*1024*1024)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" {
			continue
		}
		var row factRow
		if err := json.Unmarshal([]byte(line), &row); err != nil {
			t.Fatalf("parse %s: %v", path, err)
		}
		out[row.ID] = row.AmountCents
	}
	if err := sc.Err(); err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	if len(out) == 0 {
		t.Fatalf("%s carries no facts, so this test asserts nothing", path)
	}
	return out
}

// The column is held to facts/facts.jsonl, not to the files it replaces: a
// golden regenerated by the commit that changes the format is green by
// construction. A derived link cites nothing and is counted rather than skipped.
//
// Why, measured: docs/schema-contracts.md.
func TestEveryColumnLinkEqualsTheFactsItCites(t *testing.T) {
	facts := committedFacts(t)
	built, err := buildAll(repoRootForTest(t))
	if err != nil {
		t.Fatalf("buildAll: %v", err)
	}
	columns, err := export.ColumnsOf(built.Projections)
	if err != nil {
		t.Fatalf("columnsOf: %v", err)
	}
	if len(columns) == 0 {
		t.Fatal("no column document was built, so this test asserts nothing")
	}

	checked, derived, flipped := 0, 0, 0
	for name, col := range columns {
		for schedule, sched := range col.Schedules {
			for i, l := range sched.Links {
				if len(l.FactIDs) == 0 {
					if !l.Derived {
						t.Errorf("%s %s link %d cites no fact and is not marked derived; "+
							"every published figure carries a provenance pointer",
							name, schedule, i)
					}
					derived++
					continue
				}
				var sum int64
				missing := []string(nil)
				for _, id := range l.FactIDs {
					cents, ok := facts[id]
					if !ok {
						missing = append(missing, id)
						continue
					}
					sum += cents
				}
				if len(missing) > 0 {
					t.Errorf("%s %s link %d cites %v, which facts/facts.jsonl does not carry",
						name, schedule, i, missing)
					continue
				}
				// The draw leg carries the negation of its facts; the same
				// allowance internal/check's link-values-tie-to-facts makes.
				// The condition is the source node id and not the sign of the
				// sum, because "equals the absolute sum" accepts a leg pointing
				// the wrong way.
				want := sum
				if col.Nodes[l.From].ID == project.NodeFundBalanceDraw {
					want = -sum
					flipped++
				}
				if want != l.ValueCents {
					t.Errorf("%s %s link %d (%s -> %s) carries %d and its %d fact(s) come to %d",
						name, schedule, i, col.Nodes[l.From].ID, col.Nodes[l.To].ID,
						l.ValueCents, len(l.FactIDs), sum)
				}
				checked++
			}
		}
	}
	t.Logf("%d cited link(s) across %d column(s) equal the facts they cite, "+
		"%d of them the fund-balance draw carrying their negation; %d derived link(s) cite nothing",
		checked, len(columns), flipped, derived)
	// The allowance is not vacuous.
	if flipped == 0 {
		t.Error("no fund-balance draw was checked, so the one allowance this test " +
			"makes was never exercised and could be wrong")
	}
}

// The indices resolve. An off-by-one joins the wrong marks while every figure
// stays correct, which no fact check can see.
func TestEveryColumnIndexResolves(t *testing.T) {
	built, err := buildAll(repoRootForTest(t))
	if err != nil {
		t.Fatalf("buildAll: %v", err)
	}
	columns, err := export.ColumnsOf(built.Projections)
	if err != nil {
		t.Fatalf("columnsOf: %v", err)
	}
	for name, col := range columns {
		seen := map[int]bool{}
		for _, tier := range col.Tiers {
			for _, i := range tier.Nodes {
				if i < 0 || i >= len(col.Nodes) {
					t.Fatalf("%s tier %d names node %d of %d", name, tier.Tier, i, len(col.Nodes))
				}
				if col.Nodes[i].Tier != tier.Tier {
					t.Errorf("%s tier %d holds %s, which is tier %d",
						name, tier.Tier, col.Nodes[i].ID, col.Nodes[i].Tier)
				}
				if seen[i] {
					t.Errorf("%s lists node %s in two tiers", name, col.Nodes[i].ID)
				}
				seen[i] = true
			}
		}
		if len(seen) != len(col.Nodes) {
			t.Errorf("%s: the tier lists reach %d of %d nodes, so some node stands in no column",
				name, len(seen), len(col.Nodes))
		}
		for schedule, sched := range col.Schedules {
			for _, n := range sched.Nodes {
				if n.Node < 0 || n.Node >= len(col.Nodes) {
					t.Fatalf("%s %s draws node %d of %d", name, schedule, n.Node, len(col.Nodes))
				}
			}
			for i, l := range sched.Links {
				if l.From < 0 || l.From >= len(col.Nodes) || l.To < 0 || l.To >= len(col.Nodes) {
					t.Fatalf("%s %s link %d joins %d -> %d, and the table holds %d",
						name, schedule, i, l.From, l.To, len(col.Nodes))
				}
			}
		}
	}
}
